<a href="https://colab.research.google.com/github/victorlee0923-creator/Pytorch-tutorials/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import torch
import numpy as np

##List

In [2]:
my_list=[[1,2,3,4],[6,7,8,9,10]]
print(my_list)

[[1, 2, 3, 4], [6, 7, 8, 9, 10]]


##NUMPY ARRAYS

In [5]:
#這裡可以回去看一下光頭之前講的關於numpy的影片
np1=np.random.rand(3,4)
print(np1)

[[0.22399254 0.61723927 0.84917338 0.32679133]
 [0.32513125 0.7863243  0.69172016 0.33231006]
 [0.37902895 0.42497038 0.1561022  0.94043662]]


In [7]:
print(type(np1))
np1.dtype

<class 'numpy.ndarray'>


dtype('float64')