<a href="https://colab.research.google.com/github/victorlee0923-creator/Pytorch-tutorials/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

##List

In [2]:
my_list=[[1,2,3,4],[6,7,8,9,10]]
print(my_list)

[[1, 2, 3, 4], [6, 7, 8, 9, 10]]


##NUMPY ARRAYS

In [3]:
#這裡可以回去看一下光頭之前講的關於numpy的影片
np1=np.random.rand(3,4)
print(np1)

[[0.98777413 0.13593139 0.17116438 0.3204523 ]
 [0.76451293 0.60725896 0.09517728 0.89478821]
 [0.27437423 0.23482858 0.08172571 0.97886055]]


In [4]:
print(type(np1))
np1.dtype

<class 'numpy.ndarray'>


dtype('float64')

In [5]:
tensor_2d=torch.rand(3,4)
print(tensor_2d)

tensor([[0.4210, 0.3027, 0.7453, 0.4023],
        [0.8633, 0.2891, 0.1523, 0.1474],
        [0.2439, 0.0326, 0.6721, 0.7317]])
