<a href="https://colab.research.google.com/github/victorlee0923-creator/Pytorch-tutorials/blob/main/%E9%98%BF%E6%8B%89%E4%B8%81_2_Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch

In [3]:
# my_tensor=torch.tensor([[1,2,3],[4,5,6]],dtype=torch.float32,device='cuda',requires_grad=True)
# print(my_tensor)


##Initializing tensors

In [4]:
device="cuda" if torch.cuda.is_available() else "cpu"
my_tensor=torch.tensor([[1,2,3],[4,5,6]],dtype=torch.float32,device=device,requires_grad=True)

In [5]:
#原文書中的tensor initialize的做法
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [6]:
#印出tensor的屬性
print(my_tensor)
print(my_tensor.dtype)
print(my_tensor.device)
print(my_tensor.shape)
print(my_tensor.requires_grad)

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0', requires_grad=True)
torch.float32
cuda:0
torch.Size([2, 3])
True


##Other common initialization methods

In [7]:
#其他初始化tensor的方法 Other common initialization methods

x=torch.empty(size=(3,3)) #如果不知道要輸入甚麼value到tensor，可以用這個，內容是隨機的內存殘留值
x=torch.zeros(size=(3,3)) #全部設為0
x=torch.ones(size=(3,3)) #全部初始化為1
x=torch.rand(size=(3,3)) #隨機初始化 範圍從0~1
x=torch.eye(5,5) #單位矩陣 eye是I的諧音

x=torch.arange(start=0,end=5,step=1) #這就跟python中的range沒什麼兩樣
x=torch.linspace(start=0.1,end=1,steps=10) #等差數列，創建一個包含 10 個等間距數值的一維張量，範圍從 0.1 到 1（包含兩端點）
x=torch.empty(size=(1,5)).normal_(mean=0,std=1) #問ai
x=torch.empty(size=(1,5)).uniform_(0,1) #問ai
x=torch.diag(torch.ones(3)) #創建3X3對角矩陣
x=torch.diag(torch.tensor([2,4,6])) #設定值不全為1的對角矩陣

print(x)

tensor([[2, 0, 0],
        [0, 4, 0],
        [0, 0, 6]])


In [8]:
#記住，以下這幾行的size可加可不加(原影片中沒加)

x=torch.empty((3,3))
x=torch.zeros((3,3))
x=torch.ones((3,3))
x=torch.rand((3,3))

#以下為一些補充操作
print(x[0]) #取用此多維tensor中的特定row
#以下取用此多維tensor中的特定元素
value = x[0, 1]
print(value)


tensor([0.4582, 0.3709, 0.9714])
tensor(0.3709)


##How to initialize and convert tensors to other types

In [9]:
# How to initialize and convert tensors to other types (int, float, double)

tensor=torch.arange(4)
print(tensor.bool())
print(tensor.short())
print(tensor.long())
print(tensor.half())
print(tensor.float())
print(tensor.double())

tensor([False,  True,  True,  True])
tensor([0, 1, 2, 3], dtype=torch.int16)
tensor([0, 1, 2, 3])
tensor([0., 1., 2., 3.], dtype=torch.float16)
tensor([0., 1., 2., 3.])
tensor([0., 1., 2., 3.], dtype=torch.float64)


##Array to Tensor conversion and vice-versa

In [10]:
#Array to Tensor conversion and vice-versa
import numpy as np
np_array=np.zeros((5,5))
tensor=torch.from_numpy(np_array)#轉換為tensor
np_array_back=tensor.numpy()#轉換回numpy

##Tensor math

In [11]:
#tensor的運算 (使用兩個預先建立好的tensor來做為範例說明)
x=torch.tensor([1,2,3])
y=torch.tensor([10,20,30])

In [12]:
#tensor的加法
#第一種相加作法

z1=torch.empty(3)
torch.add(x,y,out=z1)
print(z1)

#第二種相加作法
z2=torch.add(x,y)
print(z2)

#第三種相加法 (作者本人首選)
z=x+y
print(z)

tensor([11., 22., 33.])
tensor([11, 22, 33])
tensor([11, 22, 33])


In [13]:
#tensor的減法
z=y-x
print(z)

tensor([ 9, 18, 27])


In [14]:
#rensor除法
z=torch.true_divide(y,x)
print(z)

tensor([10., 10., 10.])


In [15]:
#inplace operation
t=torch.zeros(3)
t.add_(x) #看到底線就可以知道是inplace
print(t)

#另一種inplace operation
a=torch.zeros(3)
a+=y #如果使用a=a+y則不會是inplece，而會創造一個copy
print(a)

tensor([1., 2., 3.])
tensor([10., 20., 30.])


In [16]:
#exponentiation (冪運算)
z=x.pow(2)
print(z)
z=x**2 #阿拉丁是推薦這個做法

tensor([1, 4, 9])


In [17]:
#simple comparison 簡單的比較
#逐一比較所有的element和0進行比較
z=x>0
z=x<0
print(z)


tensor([False, False, False])


In [18]:
#Matrix Multiplication 矩陣乘法
x1=torch.rand((2,5))
x2=torch.rand((5,3))
x3=torch.mm(x1,x2) #變成一個2X3矩陣
x4=x1.mm(x2) #另一種寫法
print(x3)

tensor([[1.3494, 1.6213, 1.3531],
        [1.8491, 1.4425, 0.9212]])


In [19]:
#matrix exponentiation 矩陣冪運算
matrix_exp=torch.rand((5,5))
print(matrix_exp.matrix_power(3)) #matrix_power用來計算matrix的整數次方AxAxA這種

tensor([[2.4074, 3.1739, 3.1915, 3.4285, 3.7444],
        [1.2635, 1.7492, 1.6275, 1.7982, 1.8772],
        [3.3643, 4.7994, 4.7036, 4.9928, 5.0900],
        [2.6903, 3.5811, 4.0058, 4.0734, 4.2642],
        [3.0426, 4.0479, 4.4111, 4.5677, 4.7200]])


In [20]:
#element wise muitiplication  逐元素相乘
z=x*y
print(z)


tensor([10, 40, 90])


In [21]:
#dot product 積之和
z=torch.dot(x,y)
print(z)

tensor(140)


In [22]:
# batch matrix multiplication 24:54
batch=32
n=10
m=20
p=30

tensor1=torch.rand((batch,n,m))
tensor2=torch.rand((batch,m,p))
out_bmm=torch.bmm(tensor1,tensor2)
print(out_bmm.shape)

torch.Size([32, 10, 30])


In [23]:
#broadcasting
x1=torch.rand((5,5))
x2=torch.rand((1,5)) #自動擴展變成(5,5)
z=x1-x2
print(z)
z=x1**x2
print(z)

tensor([[-0.3540, -0.0619,  0.0782, -0.2968,  0.8636],
        [-0.3363,  0.6948,  0.0577, -0.0869,  0.4969],
        [-0.3489,  0.5960,  0.0996, -0.7285,  0.6768],
        [ 0.2414,  0.6463, -0.7374, -0.7373,  0.7923],
        [-0.2433, -0.2231, -0.4008, -0.3237,  0.2981]])
tensor([[0.4648, 0.6555, 0.8837, 0.6762, 0.9957],
        [0.4819, 0.9892, 0.8672, 0.8804, 0.9531],
        [0.4697, 0.9611, 0.9008, 0.2474, 0.9764],
        [0.9433, 0.9757, 0.0775, 0.2384, 0.9888],
        [0.5676, 0.4313, 0.4665, 0.6499, 0.9183]])


###Other useful tensor operation

In [24]:
#sum
x2=torch.rand((2,5))
sum_x=torch.sum(x2,dim=1) #調整看看


In [25]:
#回傳最大值以及其index
value,indicies=torch.max(x2,dim=0)
value,indicies=torch.min(x2,dim=0)

In [26]:
#回傳絕對值
abs_x2=torch.abs(x2)

In [27]:
#只回傳最大或最小值的index
z=torch.argmax(x2,dim=0) #找出最大值的index
z=torch.argmin(x2,dim=0)

In [28]:
#計算平均值
mean_x=torch.mean(x.float(),dim=0)

In [29]:
#比較兩向量或矩陣
z=torch.eq(x,y)
z

tensor([False, False, False])

In [33]:
#排序
sorted_y,indicies=torch.sort(y,dim=0,descending=False) #decending可以控制升冪或是降冪
print(sorted_y)
print(indicies)

tensor([10, 20, 30])
tensor([0, 1, 2])


In [36]:
#32: 30 clamp 限制數字範圍
x=torch.tensor([11,12,1,2,-1])
z=torch.clamp(x,min=0,max=10)
z

tensor([10, 10,  1,  2,  0])

In [43]:
x=torch.tensor([0,0,0,0,0],dtype=bool)
y=torch.tensor([1,0,0,0,0],dtype=bool)
#any就是只要有一個是1就會為true
z=torch.any(x)
z1=torch.any(y)
print(z)
print(z1)

tensor(False)
tensor(True)


In [45]:
x=torch.tensor([1,1,1,1,1],dtype=bool)
y=torch.tensor([1,0,0,0,0],dtype=bool)
#all就是全部都要是1才會為true
z=torch.all(x)
z1=torch.all(y)
print(z)
print(z1)

tensor(True)
tensor(False)


##Tensor indexing

In [59]:
#基本的indexing
batch_size=10
features=25
x=torch.rand((batch_size,features))
print(x[0].shape) #相當於x[0,:] 取得所有二維的東西(所有feature)
print(x[:,0].shape) #相反，取得所有batch_size
print(x[2,0:5]) #第二個row的元素index0~4

x[2,0]=30
print(x[2,0:5]) #透過前一行對元素內容進行了修改

# 把這兩個的shape拿掉看看裡面的內容物

torch.Size([25])
torch.Size([10])
tensor([0.9543, 0.5122, 0.1341, 0.0538, 0.0841])
tensor([30.0000,  0.5122,  0.1341,  0.0538,  0.0841])


In [60]:
#37.51
x=torch.arange(10) #創建一個從 0 到 9 的一維張量（tensor）
indicies=[2,5,8] #定義一個索引列表，指定要選取的元素位置
print(x[indicies]) #選取索引位置為 2、5、8 的元素

tensor([2, 5, 8])


In [ ]:
#38:49