<a href="https://colab.research.google.com/github/victorlee0923-creator/Pytorch-tutorials/blob/main/%E9%98%BF%E6%8B%89%E4%B8%81_2_Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch

In [3]:
# my_tensor=torch.tensor([[1,2,3],[4,5,6]],dtype=torch.float32,device='cuda',requires_grad=True)
# print(my_tensor)


##Initializing tensors

In [4]:
device="cuda" if torch.cuda.is_available() else "cpu"
my_tensor=torch.tensor([[1,2,3],[4,5,6]],dtype=torch.float32,device=device,requires_grad=True)

In [5]:
#原文書中的tensor initialize的做法
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [6]:
#印出tensor的屬性
print(my_tensor)
print(my_tensor.dtype)
print(my_tensor.device)
print(my_tensor.shape)
print(my_tensor.requires_grad)

tensor([[1., 2., 3.],
        [4., 5., 6.]], requires_grad=True)
torch.float32
cpu
torch.Size([2, 3])
True


##Other common initialization methods

In [7]:
#其他初始化tensor的方法 Other common initialization methods

x=torch.empty(size=(3,3)) #如果不知道要輸入甚麼value到tensor，可以用這個，內容是隨機的內存殘留值
x=torch.zeros(size=(3,3)) #全部設為0
x=torch.ones(size=(3,3)) #全部初始化為1
x=torch.rand(size=(3,3)) #隨機初始化 範圍從0~1
x=torch.eye(5,5) #單位矩陣 eye是I的諧音

x=torch.arange(start=0,end=5,step=1) #這就跟python中的range沒什麼兩樣
x=torch.linspace(start=0.1,end=1,steps=10) #等差數列，創建一個包含 10 個等間距數值的一維張量，範圍從 0.1 到 1（包含兩端點）
x=torch.empty(size=(1,5)).normal_(mean=0,std=1) #問ai
x=torch.empty(size=(1,5)).uniform_(0,1) #問ai
x=torch.diag(torch.ones(3)) #創建3X3對角矩陣
x=torch.diag(torch.tensor([2,4,6])) #設定值不全為1的對角矩陣

print(x)

tensor([[2, 0, 0],
        [0, 4, 0],
        [0, 0, 6]])


In [8]:
#記住，以下這幾行的size可加可不加(原影片中沒加)

x=torch.empty((3,3))
x=torch.zeros((3,3))
x=torch.ones((3,3))
x=torch.rand((3,3))

#以下為一些補充操作
print(x[0]) #取用此多維tensor中的特定row
#以下取用此多維tensor中的特定元素
value = x[0, 1]
print(value)


tensor([0.4679, 0.5561, 0.1231])
tensor(0.5561)


##How to initialize and convert tensors to other types

In [9]:
# How to initialize and convert tensors to other types (int, float, double)

tensor=torch.arange(4)
print(tensor.bool())
print(tensor.short())
print(tensor.long())
print(tensor.half())
print(tensor.float())
print(tensor.double())

tensor([False,  True,  True,  True])
tensor([0, 1, 2, 3], dtype=torch.int16)
tensor([0, 1, 2, 3])
tensor([0., 1., 2., 3.], dtype=torch.float16)
tensor([0., 1., 2., 3.])
tensor([0., 1., 2., 3.], dtype=torch.float64)


##Array to Tensor conversion and vice-versa

In [10]:
#Array to Tensor conversion and vice-versa
import numpy as np
np_array=np.zeros((5,5))
tensor=torch.from_numpy(np_array)#轉換為tensor
np_array_back=tensor.numpy()#轉換回numpy

##Tensor math

In [11]:
#tensor的運算 (使用兩個預先建立好的tensor來做為範例說明)
x=torch.tensor([1,2,3])
y=torch.tensor([10,20,30])

In [30]:
#tensor的加法
#第一種相加作法

z1=torch.empty(3)
torch.add(x,y,out=z1)
print(z1)

#第二種相加作法
z2=torch.add(x,y)
print(z2)

#第三種相加法 (作者本人首選)
z=x+y
print(z)

tensor([11., 22., 33.])
tensor([11, 22, 33])
tensor([11, 22, 33])


In [ ]:
#tensor的減法
z=y-x
print(z)

#rensor除法
z=torch.true_divide(y,x)
print(z)

#inplace operation
t=torch.zeros(3)
t.add_(x) #看到底線就可以知道是inplace
print(t)

#另一種inplace operation
a=torch.zeros(3)
a+=y #如果使用a=a+y則不會是inplece，而會創造一個copy
print(a)

#exponentiation (冪運算)
z=x.pow(2)
print(z)
z=x**2 #阿拉丁是推薦這個做法

In [ ]:
#simple comparison 簡單的比較
#逐一比較所有的element和0進行比較
z=x>0
z=x<0
print(z)

#Matrix Multiplication 矩陣乘法
x1=torch.rand((2,5))
x2=torch.rand((5,3))
x3=torch.mm(x1,x2) #變成一個2X3矩陣
x4=x1.mm(x2) #另一種寫法
print(x3)

#matrix exponentiation 矩陣冪運算
matrix_exp=torch.rand((5,5))
print(matrix_exp.matrix_power(3)) #matrix_power用來計算matrix的整數次方AxAxA這種

#element wise muitiplication  逐元素相乘
z=x*y
print(z)



In [ ]:
#dot product 積之和
z=torch.dot(x,y)
print(z)

# batch matrix multiplication 24:54